name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Create zip without version tag
        run: cd .. && zip -r -x '.git/*' -x '.github/*' ${{ github.event.repository.name }}-${{ github.ref }}.zip ${{ github.event.repository.name }}
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: ${{ github.event.commits[0].message }} 
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Attach Zip File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../${{ github.event.repository.name }}-${{ github.ref }}.zip
          asset_name: ${{ github.event.repository.name }}-${{ github.ref }}.zip
          asset_content_type: application/zip
